apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: laexqn3t0-nodejs-gitops
  description: This is GitOps manifest for laexqn3t0-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=laexqn3t0-nodejs
    backstage.io/kubernetes-id: laexqn3t0-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: laexqn3t0-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:laexqn3t0-nodejs
